version: '3'

services:
  # Servicio para tu aplicación Java/JavaFX
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgs-app
    restart: unless-stopped
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=sgs_visits_db  # Cambiado al nombre de la BD que usas
      - DATABASE_USER=sgs_user
      - DATABASE_PASSWORD=sgs_password
    network_mode: "host"  # Para X11 forwarding
    depends_on:
      - db

  # Servicio para MySQL
  db:
    image: mysql:8.0
    container_name: sgs-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=sgs_visits_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialización
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:  # Para persistencia de datos